# Generated by Django 5.0.6 on 2024-07-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_news_author_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='price',
            field=models.IntegerField(default=5000),
            preserve_default=False,
        ),
    ]
